export const country = [
  { code: 'ind', name: 'INDIA' },
  { code: 'usa', name: 'USA' },
  { code: 'dubai', name: 'DUBAI' },
  { code: 'canada', name: 'CANADA' },
  { code: 'uae', name: 'UAE' },
  { code: 'bang', name: 'BANGLADESH' },
  { code: 'nepal', name: 'NEPAL' },
];

// export const TOP_50_COUNTRIES = [
//   'China',
//   'India',
//   'United States',
//   'Indonesia',
//   'Pakistan',
//   'Bangladesh',
//   'Japan',
//   'Philippines',
//   'Vietnam',
//   'Turkey',
//   'Iran',
//   'Thailand',
//   'Myanmar',
//   'South Korea',
//   'Iraq',
//   'Afghanistan',
//   'Saudi Arabia',
//   'Malaysia',
//   'Yemen',
//   'North Korea',
//   'Syria',
//   'Uzbekistan',
//   'Jordan',
//   'Kazakhstan',
//   'Kyrgyzstan',
//   'Laos',
//   'Lebanon',
//   'Kuwait',
//   'Korea, South',
//   'Oman',
//   'State of Palestine',
//   'Qatar',
//   'Azerbaijan',
//   'Bahrain',
//   'Cambodia',
//   'United Arab Emirates',
//   'Armenia',
//   'Cyprus',
//   'Mongolia',
//   'Israel',
//   'Georgia',
//   'Timor-Leste',
//   'Maldives',
//   'Bhutan',
//   'North Macedonia',
//   'Sri Lanka',
//   'Slovakia',
//   'Turkmenistan',
// ];
