export const states = [
  { key: 'Andhra Pradesh', value: 'AP' },
  { key: 'Arunachal Pradesh', value: 'AR' },
  { key: 'Assam', value: 'AS' },
  { key: 'Bihar', value: 'BR' },
  { key: 'Chhattisgarh', value: 'CT' },
  { key: 'Goa', value: 'GA' },
  { key: 'Gujarat', value: 'GJ' },
  { key: 'Haryana', value: 'HR' },
  { key: 'Himachal Pradesh', value: 'HP' },
  { key: 'Jharkhand', value: 'JH' },
  { key: 'Karnataka', value: 'KA' },
  { key: 'Kerala', value: 'KL' },
  { key: 'Madhya Pradesh', value: 'MP' },
  { key: 'Maharashtra', value: 'MH' },
  { key: 'Manipur', value: 'MN' },
  { key: 'Meghalaya', value: 'ML' },
  { key: 'Mizoram', value: 'MZ' },
  { key: 'Nagaland', value: 'NL' },
  { key: 'Odisha', value: 'OR' },
  { key: 'Punjab', value: 'PB' },
  { key: 'Rajasthan', value: 'RJ' },
  { key: 'Sikkim', value: 'SK' },
  { key: 'Tamil Nadu', value: 'TN' },
  { key: 'Telangana', value: 'TS' },
  { key: 'Tripura', value: 'TR' },
  { key: 'Uttar Pradesh', value: 'UP' },
  { key: 'Uttarakhand', value: 'UK' },
  { key: 'West Bengal', value: 'WB' },
];
